// Mock data simulating Kalshi basketball markets

export const liveGames = [
  {
    id: 'nba-lal-bos-20260322',
    homeTeam: 'Los Angeles Lakers',
    awayTeam: 'Boston Celtics',
    homeScore: 87,
    awayScore: 91,
    quarter: 'Q4',
    timeRemaining: '4:32',
    homeWinProb: 0.34,
    awayWinProb: 0.66,
    recommendation: 'BET',
    suggestedTeam: 'away',
    marketTicker: 'KXNBA-LAL-BOS-2026-03-22',
    yesPrice: 0.66,
    noPrice: 0.34,
  },
  {
    id: 'nba-gsw-mia-20260322',
    homeTeam: 'Golden State Warriors',
    awayTeam: 'Miami Heat',
    homeScore: 55,
    awayScore: 52,
    quarter: 'Q3',
    timeRemaining: '8:15',
    homeWinProb: 0.58,
    awayWinProb: 0.42,
    recommendation: 'WATCH',
    suggestedTeam: null,
    marketTicker: 'KXNBA-GSW-MIA-2026-03-22',
    yesPrice: 0.58,
    noPrice: 0.42,
  },
  {
    id: 'nba-den-phi-20260322',
    homeTeam: 'Denver Nuggets',
    awayTeam: 'Philadelphia 76ers',
    homeScore: 102,
    awayScore: 78,
    quarter: 'Q4',
    timeRemaining: '1:05',
    homeWinProb: 0.97,
    awayWinProb: 0.03,
    recommendation: 'NO ACTION',
    suggestedTeam: null,
    marketTicker: 'KXNBA-DEN-PHI-2026-03-22',
    yesPrice: 0.97,
    noPrice: 0.03,
  },
  {
    id: 'nba-nyk-dal-20260322',
    homeTeam: 'New York Knicks',
    awayTeam: 'Dallas Mavericks',
    homeScore: 24,
    awayScore: 28,
    quarter: 'Q2',
    timeRemaining: '9:44',
    homeWinProb: 0.45,
    awayWinProb: 0.55,
    recommendation: 'BET',
    suggestedTeam: 'away',
    marketTicker: 'KXNBA-NYK-DAL-2026-03-22',
    yesPrice: 0.55,
    noPrice: 0.45,
  },
];

export const betHistory = [
  {
    id: 1,
    date: '2026-03-21',
    team: 'Boston Celtics',
    opponent: 'Chicago Bulls',
    side: 'YES',
    entryPrice: 0.62,
    result: 'WIN',
    payout: 1.0,
    profit: 0.38,
    stake: 50,
  },
  {
    id: 2,
    date: '2026-03-21',
    team: 'Golden State Warriors',
    opponent: 'Houston Rockets',
    side: 'YES',
    entryPrice: 0.71,
    result: 'LOSS',
    payout: 0.0,
    profit: -0.71,
    stake: 30,
  },
  {
    id: 3,
    date: '2026-03-20',
    team: 'Denver Nuggets',
    opponent: 'Sacramento Kings',
    side: 'YES',
    entryPrice: 0.55,
    result: 'WIN',
    payout: 1.0,
    profit: 0.45,
    stake: 40,
  },
  {
    id: 4,
    date: '2026-03-20',
    team: 'Miami Heat',
    opponent: 'Cleveland Cavaliers',
    side: 'NO',
    entryPrice: 0.40,
    result: 'WIN',
    payout: 1.0,
    profit: 0.60,
    stake: 25,
  },
  {
    id: 5,
    date: '2026-03-19',
    team: 'Dallas Mavericks',
    opponent: 'Phoenix Suns',
    side: 'YES',
    entryPrice: 0.48,
    result: 'LOSS',
    payout: 0.0,
    profit: -0.48,
    stake: 35,
  },
];
